<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WL" ignored="0" name="Test" tests="6" failures="2" timestamp="12 三月 2018 10:07:03 GMT" time="35.696" errors="0">
  <testcase name="function1" time="11.773" classname="ftnt.qa.autotest.ui.fortisiem.pageobject.test">
    <skipped/>
  </testcase> <!-- function1 -->
  <testcase name="function1" time="18.695" classname="ftnt.qa.autotest.ui.fortisiem.pageobject.test">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at ftnt.qa.autotest.ui.fortisiem.pageobject.test.function1(test.java:36)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- function1 -->
  <testcase name="function2" time="0.002" classname="ftnt.qa.autotest.ui.fortisiem.pageobject.test"/>
  <testcase name="function3" time="0.0" classname="ftnt.qa.autotest.ui.fortisiem.pageobject.test">
    <skipped/>
  </testcase> <!-- function3 -->
  <testcase name="function3" time="0.0" classname="ftnt.qa.autotest.ui.fortisiem.pageobject.test">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at ftnt.qa.autotest.ui.fortisiem.pageobject.test.function3(test.java:46)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- function3 -->
  <testcase name="function4" time="0.001" classname="ftnt.qa.autotest.ui.fortisiem.pageobject.test"/>
</testsuite> <!-- Test -->
