<html>
<head>
<title>TestNG:  Test</title>
<link href="../testng.css" rel="stylesheet" type="text/css" />
<link href="../my-testng.css" rel="stylesheet" type="text/css" />

<style type="text/css">
.log { display: none;} 
.stack-trace { display: none;} 
</style>
<script type="text/javascript">
<!--
function flip(e) {
  current = e.style.display;
  if (current == 'block') {
    e.style.display = 'none';
    return 0;
  }
  else {
    e.style.display = 'block';
    return 1;
  }
}

function toggleBox(szDivId, elem, msg1, msg2)
{
  var res = -1;  if (document.getElementById) {
    res = flip(document.getElementById(szDivId));
  }
  else if (document.all) {
    // this is the way old msie versions work
    res = flip(document.all[szDivId]);
  }
  if(elem) {
    if(res == 0) elem.innerHTML = msg1; else elem.innerHTML = msg2;
  }

}

function toggleAllBoxes() {
  if (document.getElementsByTagName) {
    d = document.getElementsByTagName('div');
    for (i = 0; i < d.length; i++) {
      if (d[i].className == 'log') {
        flip(d[i]);
      }
    }
  }
}

// -->
</script>

</head>
<body>
<h2 align='center'>Test</h2><table border='1' align="center">
<tr>
<td>Tests passed/Failed/Skipped:</td><td>6/1/3</td>
</tr><tr>
<td>Started on:</td><td>Fri Apr 20 10:30:50 CST 2018</td>
</tr>
<tr><td>Total time:</td><td>72 seconds (72989 ms)</td>
</tr><tr>
<td>Included groups:</td><td></td>
</tr><tr>
<td>Excluded groups:</td><td></td>
</tr>
</table><p/>
<small><i>(Hover the method name to see the test class name)</i></small><p/>
<table width='100%' border='1' class='invocation-failed'>
<tr><td colspan='4' align='center'><b>FAILED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='ftnt.qa.autotest.ui.fortisiem.testcases.User.function2()'><b>function2</b><br>Test class: ftnt.qa.autotest.ui.fortisiem.testcases.User</td>
<td><div><pre>java.lang.AssertionError: expected [true] but found [false]
	at ftnt.qa.autotest.ui.fortisiem.testcases.User.function2(User.java:20)
... Removed 29 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace1508059488", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1508059488'><pre>java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertTrue(Assert.java:44)
	at org.testng.Assert.assertTrue(Assert.java:54)
	at ftnt.qa.autotest.ui.fortisiem.testcases.User.function2(User.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:838)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1009)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</pre></div></td>
<td>0</td>
<td>ftnt.qa.autotest.ui.fortisiem.testcases.User@61009542</td></tr>
</table><p>
<table width='100%' border='1' class='invocation-passed'>
<tr><td colspan='4' align='center'><b>PASSED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='ftnt.qa.autotest.ui.fortisiem.testcases.Organization.function1()'><b>function1</b><br>Test class: ftnt.qa.autotest.ui.fortisiem.testcases.Organization</td>
<td></td>
<td>5</td>
<td>ftnt.qa.autotest.ui.fortisiem.testcases.Organization@77e9807f</td></tr>
<tr>
<td title='ftnt.qa.autotest.ui.fortisiem.testcases.Credentials.test1()'><b>test1</b><br>Test class: ftnt.qa.autotest.ui.fortisiem.testcases.Credentials</td>
<td></td>
<td>5</td>
<td>ftnt.qa.autotest.ui.fortisiem.testcases.Credentials@448ff1a8</td></tr>
<tr>
<td title='ftnt.qa.autotest.ui.fortisiem.testcases.Credentials.test2()'><b>test2</b><br>Test class: ftnt.qa.autotest.ui.fortisiem.testcases.Credentials</td>
<td></td>
<td>3</td>
<td>ftnt.qa.autotest.ui.fortisiem.testcases.Credentials@448ff1a8</td></tr>
<tr>
<td title='ftnt.qa.autotest.ui.fortisiem.testcases.Credentials.test3()'><b>test3</b><br>Test class: ftnt.qa.autotest.ui.fortisiem.testcases.Credentials</td>
<td></td>
<td>2</td>
<td>ftnt.qa.autotest.ui.fortisiem.testcases.Credentials@448ff1a8</td></tr>
<tr>
<td title='ftnt.qa.autotest.ui.fortisiem.testcases.Credentials.test4()'><b>test4</b><br>Test class: ftnt.qa.autotest.ui.fortisiem.testcases.Credentials</td>
<td></td>
<td>5</td>
<td>ftnt.qa.autotest.ui.fortisiem.testcases.Credentials@448ff1a8</td></tr>
<tr>
<td title='ftnt.qa.autotest.ui.fortisiem.testcases.Credentials.test5()'><b>test5</b><br>Test class: ftnt.qa.autotest.ui.fortisiem.testcases.Credentials</td>
<td></td>
<td>5</td>
<td>ftnt.qa.autotest.ui.fortisiem.testcases.Credentials@448ff1a8</td></tr>
</table><p>
<table width='100%' border='1' class='invocation-skipped'>
<tr><td colspan='4' align='center'><b>SKIPPED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='ftnt.qa.autotest.ui.fortisiem.testcases.User.function2()'><b>function2</b><br>Test class: ftnt.qa.autotest.ui.fortisiem.testcases.User<br/>
<a href="#Output-1515403487" onClick='toggleBox("Output-1515403487", this, "Show output", "Hide output");'>Show output</a>

<a href="#Output-1515403487" onClick="toggleAllBoxes();">Show all outputs</a>
<div class='log' id="Output-1515403487">
方法<function2>执行失败，重试第1次<br/>
</div>
</td>
<td><div><pre>java.lang.AssertionError: expected [true] but found [false]
	at ftnt.qa.autotest.ui.fortisiem.testcases.User.function2(User.java:20)
... Removed 29 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace1515403487", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1515403487'><pre>java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertTrue(Assert.java:44)
	at org.testng.Assert.assertTrue(Assert.java:54)
	at ftnt.qa.autotest.ui.fortisiem.testcases.User.function2(User.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</pre></div></td>
<td>0</td>
<td>ftnt.qa.autotest.ui.fortisiem.testcases.User@61009542</td></tr>
<tr>
<td title='ftnt.qa.autotest.ui.fortisiem.testcases.User.function2()'><b>function2</b><br>Test class: ftnt.qa.autotest.ui.fortisiem.testcases.User<br/>
<a href="#Output-554868511" onClick='toggleBox("Output-554868511", this, "Show output", "Hide output");'>Show output</a>

<a href="#Output-554868511" onClick="toggleAllBoxes();">Show all outputs</a>
<div class='log' id="Output-554868511">
方法<function2>执行失败，重试第2次<br/>
</div>
</td>
<td><div><pre>java.lang.AssertionError: expected [true] but found [false]
	at ftnt.qa.autotest.ui.fortisiem.testcases.User.function2(User.java:20)
... Removed 29 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace554868511", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace554868511'><pre>java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertTrue(Assert.java:44)
	at org.testng.Assert.assertTrue(Assert.java:54)
	at ftnt.qa.autotest.ui.fortisiem.testcases.User.function2(User.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:838)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1009)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</pre></div></td>
<td>0</td>
<td>ftnt.qa.autotest.ui.fortisiem.testcases.User@61009542</td></tr>
<tr>
<td title='ftnt.qa.autotest.ui.fortisiem.testcases.User.function2()'><b>function2</b><br>Test class: ftnt.qa.autotest.ui.fortisiem.testcases.User<br/>
<a href="#Output-1332691311" onClick='toggleBox("Output-1332691311", this, "Show output", "Hide output");'>Show output</a>

<a href="#Output-1332691311" onClick="toggleAllBoxes();">Show all outputs</a>
<div class='log' id="Output-1332691311">
方法<function2>执行失败，重试第3次<br/>
</div>
</td>
<td><div><pre>java.lang.AssertionError: expected [true] but found [false]
	at ftnt.qa.autotest.ui.fortisiem.testcases.User.function2(User.java:20)
... Removed 29 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace1332691311", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1332691311'><pre>java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertTrue(Assert.java:44)
	at org.testng.Assert.assertTrue(Assert.java:54)
	at ftnt.qa.autotest.ui.fortisiem.testcases.User.function2(User.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:838)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1009)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</pre></div></td>
<td>0</td>
<td>ftnt.qa.autotest.ui.fortisiem.testcases.User@61009542</td></tr>
</table><p>
</body>
</html>